language: node_js
sudo: required
node_js:
  - 10.8.0
install:
  - yarn
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test
after_success:
  - chmod ugo+x ./deploy.sh
  - ./deploy.sh
